function GetSongArt(songtit)

	local DiscImg = {
		["CHIP'N'DALE'S VACATION"] = "01",
		["チップとデールのバケーション"] = "01",
		["DISCO MAGIC"] = "02",
		["ディスコマジック"] = "02",
		["ELECTRICAL PARADE"] = "03",
		["エレクトリカル・パレード"] = "03",
		["GO GO GO"] = "04",
		["ゴー・ゴー・ゴー"] = "04",
		["GOOFY'S ROCK'N'ROLL SHOW"] = "05",
		["グーフィーのロックンロールショー"] = "05",
		["IRISH RIVER"] = "06",
		["アイリッシュリバー"] = "06",
		["IT'S A SMALL WORLD"] = "07",
		["イッツ・ア・スモール・ワールド"] = "07",
		["MICKEY FEVER"] = "08",
		["ミッキー・フィーバー"] = "08",
		["MICKEY MOTION"] = "09",
		["ミッキー・モーション"] = "09",
		["MICKEY MOUSE MARCH"] = "10",
		["ミッキーマウス・マーチ"] = "10",
		["MICKEY MOUSE ONDO"] = "11",
		["ミッキーマウス音頭"] = "11",
		["MINNIE'S YOO HOO!"] = "12",
		["ミニーのユーフー!"] = "12",
		["ミニーのユーフー！"] = "12",
		["MIWAKU NO TANGO"] = "13",
		["魅惑のタンゴ"] = "13",
		["MORTY & FERDY'S CARNIVAL"] = "14",
		["モーティーとフェルディのカーニバル"] = "14",
		["PARA-PARA VENUS"] = "15",
		["パラパラビーナス"] = "15",
		["パラパラヴィーナス"] = "15",
		["RUSSIAN DANCE"] = "16",
		["ロシアの踊り"] = "16",
		["SAVANNA NO MUKOU"] = "17",
		["サバンナのむこう"] = "17",
		["TAIYO NO RAKUEN"] = "18",
		["太陽の楽園"] = "18",
		["TAP! TAP! TAP!"] = "19",
		["タップ! タップ! タップ!"] = "19",
		["タップ！タップ！タップ！"] = "19",
		["THE TIKI TIKI TIKI ROOM"] = "20",
		["魅惑のチキルーム"] = "20",
		["TURKEY IN THE STRAW"] = "21",
		["藁の中の七面鳥"] = "21",
		["WALTZ OF THE FLOWERS"] = "22",
		["花のワルツ"] = "22",
	}

	return DiscImg[songtit] or "fallback";
end;